export const prioritySoccerEventKeys = [
  "soccer_epl",
  "soccer_spain_la_liga",
  "soccer_france_ligue_one",
  "soccer_germany_bundesliga",
  "soccer_italy_serie_a",
  "soccer_fifa_world_cup_qualifiers_europe",
  "soccer_fifa_world_cup_qualifiers_south_america",
  "soccer_uefa_nations_league",
  "soccer_africa_cup_of_nations",
  "soccer_uefa_champs_league",
  "soccer_uefa_europa_league",
  "soccer_uefa_europa_conference_league",
  "soccer_fifa_world_cup",
  "soccer_conmebol_copa_america",
  "soccer_conmebol_copa_libertadores",
  "soccer_conmebol_copa_sudamericana",
  "soccer_efl_champ",
  "soccer_netherlands_eredivisie",
  "soccer_portugal_primeira_liga",
  "soccer_usa_mls",
  "soccer_brazil_campeonato",
  "soccer_brazil_serie_b",
  "soccer_argentina_primera_division",
  "soccer_mexico_ligamx",
  "soccer_saudi_arabia_pro_league",
  "soccer_turkey_super_league",
  "soccer_spl",
] as const;

export const dailyPrioritySoccerOddsKeys = prioritySoccerEventKeys.slice(0, 8);
