import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";

const migrationsRoot = resolve(process.cwd(), "prisma", "migrations");
const baselineName = "0_init";
const baselineDir = resolve(migrationsRoot, baselineName);
const migrationFile = resolve(baselineDir, "migration.sql");
const lockFile = resolve(migrationsRoot, "migration_lock.toml");

async function existingMigrationEntries(): Promise<string[]> {
  try {
    const entries = await readdir(migrationsRoot, { withFileTypes: true });
    return entries
      .filter(
        (entry) =>
          entry.name !== "migration_lock.toml" &&
          entry.name !== ".gitkeep",
      )
      .map((entry) => entry.name);
  } catch (error) {
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "ENOENT"
    ) {
      return [];
    }
    throw error;
  }
}

async function main() {
  const existing = await existingMigrationEntries();
  if (existing.length > 0) {
    throw new Error(
      "Refusing to create a baseline because prisma/migrations already contains: " +
        existing.join(", "),
    );
  }

  await mkdir(baselineDir, { recursive: true });

  const command = process.platform === "win32" ? "npx.cmd" : "npx";
  const result = spawnSync(
    command,
    [
      "prisma",
      "migrate",
      "diff",
      "--from-empty",
      "--to-schema",
      "prisma/schema.prisma",
      "--script",
    ],
    {
      cwd: process.cwd(),
      encoding: "utf8",
      env: process.env,
    },
  );

  if (result.error || (result.status ?? 1) !== 0) {
    await rm(baselineDir, { recursive: true, force: true });
    throw result.error ?? new Error(result.stderr || "Prisma baseline generation failed.");
  }

  const sql = result.stdout.trim();
  if (!sql || !/CREATE TABLE|CREATE TYPE/.test(sql)) {
    await rm(baselineDir, { recursive: true, force: true });
    throw new Error("Prisma produced an empty or invalid baseline migration.");
  }

  await writeFile(migrationFile, sql + "\n", "utf8");
  await writeFile(
    lockFile,
    '# Please do not edit this file manually\n# It should be added in your version-control system (e.g. Git)\nprovider = "postgresql"\n',
    "utf8",
  );

  console.log("Created Prisma baseline migration:", {
    baseline: baselineName,
    migrationFile,
    bytes: Buffer.byteLength(sql, "utf8"),
  });
}

main().catch((error) => {
  console.error("EDGE baseline migration generation failed.");
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
